---
# tasks file for ansible-anbox
# Requeriments
# - name: Add Anbox PPA (Focal)
#   ansible.builtin.apt_repository:
#     repo: ppa:morphis/anbox-support
#     codename: 'focal'
#     update_cache: no
#   when: ansible_distribution_release == 'ulyana' or 
#       ansible_distribution_release == 'ulyssa' or 
#       ansible_distribution_release == 'uma' or 
#       ansible_distribution_release == 'odin' or 
#       ansible_distribution_release == 'focal'
#   register: anbox_ppa_focal
#   tags: anbox

# - name: Add Anbox PPA (Others)
#   ansible.builtin.apt_repository:
#     repo: ppa:morphis/anbox-support
#     update_cache: no
#   when: anbox_ppa_focal.skipped
#   tags: anbox

- name: apt-get update
  shell: apt-get update
  become: true
  become_user: root
  ignore_errors: yes

- name: Install Requirements packages
  apt:
    pkg:
    # - anbox-modules-dkms
    - android-tools-adb
    - build-essential
    - cmake
    - cmake-data
    - curl
    - dbus
    - debhelper
    - google-mock
    - libboost-dev 
    - libboost-filesystem-dev
    - libboost-iostreams-dev
    - libboost-log-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-test-dev
    - libboost-thread-dev
    - libcap-dev
    - libegl1-mesa-dev
    - libexpat1-dev
    - libgles2-mesa-dev
    - libglm-dev
    - libgtest-dev
    - liblxc1
    - libproperties-cpp-dev
    - libprotobuf-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libsystemd-dev
    - linux-headers-generic 
    - lxc-dev
    - lzip
    - pkg-config
    - protobuf-compiler
    - python3-minimal
    - snapd
    - software-properties-common
    - squashfs-tools
    - tar
    - unzip
    - wget
    state: present
  tags: anbox

# Enable Kernel Modules
- name: Add the ashmem_linux module
  community.general.modprobe:
    name: ashmem_linux
    state: present
  tags: anbox

- name: Add the binder_linux module
  community.general.modprobe:
    name: binder_linux
    state: present
  tags: anbox

- command: lsmod | grep -e ashmem_linux -e binder_linux
  register: result_anbox_modules
  failed_when: false
  changed_when: false
  tags: anbox

- debug:
    var: result_anbox_modules.stdout
  tags: anbox

# Anbox
- name: Install anbox snap
  shell: snap install --devmode --edge anbox
  args:
    warn: no
  # snap:
  #   name: --devmode anbox
  #   channel: latest/beta
  tags: anbox

- name: Enable Android rootfs overlay
  shell: snap set anbox rootfs-overlay.enable=true
  args:
    warn: no
  tags: anbox

- name: Restart Anbox
  shell: snap restart anbox.container-manager
  args:
    warn: no
  tags: anbox

# anbox-playstore-installer
- name: Download anbox-playstore-installer
  get_url:
    url: https://raw.githubusercontent.com/geeks-r-us/anbox-playstore-installer/master/install-playstore.sh
    dest: /opt/anbox-install-playstore.sh
    mode: '0755'
  tags: anbox

- name: Install anbox-playstore-installer
  shell: /opt/anbox-install-playstore.sh
  args:
    warn: no
  tags: anbox

# F-Droid
- name: Download F-Droid
  get_url:
    url: https://f-droid.org/F-Droid.apk
    dest: /opt/F-Droid.apk
    mode: '0755'
  tags: anbox

- name: Install F-Droid
  shell: adb install /opt/F-Droid.apk
  args:
    warn: no
  tags: anbox